version: '3.4'

services:
  todos:
    build:
      context: ${PWD}/workspace/todos
      dockerfile: Dockerfile
    image: "todos"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=true
      - FLASK_CONFIG=development
      - DEV_DATABASE_URL=postgresql://udacity:udacity@db:5432/todosapp
      - STATIC_PATH=/app/application/static
    ports:
      - "60080:80"
    volumes:
      # remove the following for production with Dockerfile ADD
      - ${PWD}/workspace/todos/application:/app/application
      - ${PWD}/workspace/todos/migrations:/app/migrations
      - ${PWD}/workspace/todos/tests:/app/tests
      - ${PWD}/workspace/todos/config.py:/app/config.py
      - ${PWD}/workspace/todos/app.py:/app/app.py
      - ${PWD}/workspace/todos/requirements.txt:/app/requirements.txt
      - ${PWD}/workspace/todos/uwsgi.ini:/app/uwsgi.ini      
    depends_on:
      - db
      - adminer

  fyyur:
    build:
      context: ${PWD}/workspace/fyyur
      dockerfile: Dockerfile
    image: "fyyur"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=true
      - FLASK_CONFIG=development
      - DEV_DATABASE_URL=postgresql://udacity:udacity@db:5432/fyyurapp
      - STATIC_PATH=/app/application/static
    ports:
      - "60080:80"
    volumes:
      # remove the following for production with Dockerfile ADD
      - ${PWD}/workspace/fyyur/application:/app/application
      - ${PWD}/workspace/fyyur/migrations:/app/migrations
      - ${PWD}/workspace/fyyur/tests:/app/tests
      - ${PWD}/workspace/fyyur/config.py:/app/config.py
      - ${PWD}/workspace/fyyur/app.py:/app/app.py
      - ${PWD}/workspace/fyyur/requirements.txt:/app/requirements.txt
      - ${PWD}/workspace/fyyur/uwsgi.ini:/app/uwsgi.ini      
    depends_on:
      - db
      - adminer

  backend:
    build:
      context: ${PWD}/workspace/flask
      dockerfile: Dockerfile
    image: "backend"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - FLASK_CONFIG=development
      - DEV_DATABASE_URL=postgresql://udacity:udacity@db:5432/todoapp
      - DATABASE_URL=postgresql://udacity:udacity@db:5432/todoapp
    ports:
      - "60080:80"
    volumes:
      # remove the following for production with Dockerfile ADD
      - ${PWD}/workspace/flask/application:/app/application
      - ${PWD}/workspace/flask/migrations:/app/migrations
      - ${PWD}/workspace/flask/tests:/app/tests
      - ${PWD}/workspace/flask/config.py:/app/config.py
      - ${PWD}/workspace/flask/main.py:/app/main.py
      - ${PWD}/workspace/flask/requirements.txt:/app/requirements.txt
      - ${PWD}/workspace/psycopg2:/workspace/psycopg2
    depends_on:
      - db
      - adminer

  db:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=udacity
      - POSTGRES_PASSWORD=udacity
      - POSTGRES_DB=udacity
    volumes:
      - ${PWD}/data:/var/lib/postgresql/data
      - ${PWD}/workspace/psql:/workspace/psql

  adminer:
    image: "adminer"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db