version: '3.4'

services:
  backend:
    build:
      context: ${PWD}/workspace/flask
      dockerfile: Dockerfile
    image: "backend"
    ports:
      - "60080:80"
    volumes:
      - ${PWD}/workspace/psycopg2:/workspace/psycopg2
    depends_on:
      - db
      - adminer

  db:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=udacity
      - POSTGRES_PASSWORD=udacity
      - POSTGRES_DB=udacity
    volumes:
      - ${PWD}/data:/var/lib/postgresql/data
      - ${PWD}/workspace/psql:/workspace/psql

  adminer:
    image: "adminer"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db