version: '3.4'

services:
  fyyur:
    build:
      context: ${PWD}/workspace/fyyur
      dockerfile: Dockerfile
    image: "fyyur"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=true
      - FLASK_CONFIG=development
      - DEV_DATABASE_URL=postgresql://udacity:udacity@db:5432/fyyurapp
      - STATIC_PATH=/app/application/static
    ports:
      - "60080:80"
    volumes:
      # remove the following for production with Dockerfile ADD
      - ${PWD}/workspace/fyyur/application:/app/application
      - ${PWD}/workspace/fyyur/data:/app/data
      - ${PWD}/workspace/fyyur/init_db.py:/app/init_db.py
      - ${PWD}/workspace/fyyur/migrations:/app/migrations
      - ${PWD}/workspace/fyyur/tests:/app/tests
      - ${PWD}/workspace/fyyur/config.py:/app/config.py
      - ${PWD}/workspace/fyyur/app.py:/app/app.py
      - ${PWD}/workspace/fyyur/requirements.txt:/app/requirements.txt
      - ${PWD}/workspace/fyyur/uwsgi.ini:/app/uwsgi.ini      
    depends_on:
      - db
      - adminer

  db:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=udacity
      - POSTGRES_PASSWORD=udacity
      - POSTGRES_DB=fyyurapp
    volumes:
      - ${PWD}/volume:/var/lib/postgresql/data
      - ${PWD}/workspace/psql:/workspace/psql

  adminer:
    image: "adminer"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db