version: '3.4'

services:
  backend:
    build:
      context: ${PWD}/workspace/flask
      dockerfile: Dockerfile
    image: "backend"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - FLASK_CONFIG=development
      - DEV_DATABASE_URL=postgresql://udacity:udacity@db:5432/todoapp
      - DATABASE_URL=postgresql://udacity:udacity@db:5432/todoapp
    ports:
      - "60080:80"
    volumes:
      # remove the following for production with Dockerfile ADD
      - ${PWD}/workspace/flask/application:/app/application
      - ${PWD}/workspace/flask/migrations:/app/migrations
      - ${PWD}/workspace/flask/tests:/app/tests
      - ${PWD}/workspace/flask/config.py:/app/config.py
      - ${PWD}/workspace/flask/main.py:/app/main.py
      - ${PWD}/workspace/flask/requirements.txt:/app/requirements.txt
      - ${PWD}/workspace/psycopg2:/workspace/psycopg2
    depends_on:
      - db
      - adminer

  db:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=udacity
      - POSTGRES_PASSWORD=udacity
      - POSTGRES_DB=udacity
    volumes:
      - ${PWD}/data:/var/lib/postgresql/data
      - ${PWD}/workspace/psql:/workspace/psql

  adminer:
    image: "adminer"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db